### ISSUE TITLE
"The file is not a correct arm64 binary" - LoginWithAmazon.framework

### ISSUE THREAD

**Issue by anfriis** [darrarski/xcframework-maker#2]
Thanks for an awesome tool!

I am trying to convert the [LoginWithAmazon.framework](https://amzndevresources.com/login-with-amazon/sdk/LoginWithAmazon_iOS.zip) using the following parameters:
```
.build/release/make-xcframework  \
  -ios LoginWithAmazon.framework \          
  -arm64sim \
  -output \output
``` 

and then I receive the following output:
```Error: The file is not a correct arm64 binary. Try thinning (via lipo) or unarchiving (via ar) first.```

Do you have any tips on how to proceed, if it is even possible?

**Comment by darrarski** [comment]
Thanks for reporting the problem. It's caused by the [arm64-to-sim](https://github.com/darrarski/arm64-to-sim), which can not read the binary for some reason. The `make-xcframework` command works as expected, but will fail when `-arm64sim` option is used.

In order to fix the issue, we will need to update `arm64-to-sim` project. I am not sure how to do it at the moment, but I am opening an [issue in its repository](https://github.com/darrarski/arm64-to-sim/issues/1).

There is no change required in the `xcframework-maker` that could fix the problem.
