### ISSUE TITLE
Error: The file is not a correct arm64 binary. Try thinning (via lipo) or unarchiving (via ar) first

### ISSUE THREAD

**Issue by ryanbooker** [darrarski/xcframework-maker#4]
Have you seen this error before? The fat framework definitely includes an arm64 slice and runs fine on device.

**Comment by darrarski** [comment]
This is a strange issue, probably caused by compiler optimization. I experienced it, but the actual problem was with `arm64-to-sim`, as described [here](https://github.com/darrarski/arm64-to-sim/issues/1). In debug mode, the `make-xcframework` will print the correct error to the console, but in release mode, the message you are seeing is printed.

For now, I don't have a fix for `arm64-to-sim`. It works with some frameworks (like GoogleCast or GoogleInteractiveMediaAds) but does not for others. 

You can omit `-arm64sim` flag when running `make-xcframework` and the XCFramework should be created for you, but without `arm64-simulator` architecture. You can also try to use `-verbose` flag to get a detailed log of what's going on when the script is run.

**Comment by markst** [comment]
Just to mention, I also experienced this when attempting to generate xcframework from `SpotifyMetadata.framework `
https://github.com/bogo/arm64-to-sim/issues/20#issuecomment-1571415755
